### ISSUE TITLE
How to edit appearance using an edited image?

### ISSUE THREAD

**Issue by xyzhang77** [ken2576/pvp#2]
Hi, 

Thank you for your excellent work. The paper mentions that we can use StyleCLIP or other methods to edit the appearance by adding direction vectors on the latent code. Is there any way we can edit the appearance using an edited image from one of the training images?

**Comment by ken2576** [comment]
Hi,

For the StyleCLIP experiment, It does not use an edited image in the training set. Instead, we have to first optimize for a latent code and then run StyleCLIP's process.
See here for more details.
https://github.com/orpatashnik/StyleCLIP/blob/main/notebooks/StyleCLIP_global_torch.ipynb

**Comment by xyzhang77** [comment]
Thanks for your response!
